name: CI
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v3

      - name: Build image
        run: |
          ctime=$(date +%Y-%m-%d)
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-${ctime}.qcow2 -- ./example/configure.sh
          qemu-img convert -f qcow2 -O vmdk -o adapter_type=lsilogic,subformat=monolithicFlat alpine-${ctime}.qcow2 alpine.vmdk

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: alpine_vmdk
          path: |
            ./alpine.vmdk
